# Generated by Django 3.2.25 on 2024-11-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_reg_date', models.DateTimeField(auto_created=True)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=64)),
                ('user_email', models.CharField(max_length=64)),
                ('user_car_cod', models.CharField(max_length=64)),
            ],
        ),
    ]
